# Centralized editable content for sophieandken.
# Every public string on the site comes from here.
# "_status": "confirmed"  -> verified wedding information, safe to publish
# "_status": "placeholder" -> sample/draft, clearly marked, replace before launch
# "_status": "hidden"      -> section framework exists but stays unpublished

CONTENT = {
    "couple": {
        "partner_one": "Sophie Knochenhauer",
        "partner_two": "Ken Syme",
        "display_names": "Sophie + Ken",
        "mark": "SK+KS",
        "tagline": "Apparently, it requires a website.",
        "_status": "confirmed",
    },
    "date": {
        "display": "Saturday, June 5, 2027",
        "short": "June 5, 2027",
        "stamp": "JUN 05 2027",
        "iso_start": "2027-06-05T17:30:00-04:00",
        "iso_end": "2027-06-06T00:30:00-04:00",
        "_status": "confirmed",
    },
    "venue": {
        "name": "New York Athletic Club",
        "address": "180 Central Park South",
        "city": "New York, New York",
        "maps_query": "New York Athletic Club, 180 Central Park South, New York, NY",
        "_status": "confirmed",
    },
    "issue": {
        "volume": "Vol. I",
        "number": "No. 1",
        "edition": "The Wedding Issue",
        "price_line": "Issued to friends & family",
        "_status": "confirmed",
    },
    "schedule": [
        {
            "time": "5:30 PM",
            "title": "Arrival",
            "description": "Come in. Get settled. Feel privately relieved that you made it on time.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "6:00 PM",
            "title": "The Ceremony",
            "description": "The part where we get married.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "6:30 PM",
            "title": "Cocktail Hour",
            "description": "An hour of cocktails.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "7:30 – 11:30 PM",
            "title": "The Reception",
            "description": "Dinner and dancing.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "11:30 PM",
            "title": "The After-Party",
            "description": "For those who, for whatever reason, would like to spend more time with the couple. Details to follow.",
            "location": "To be announced",
            "_status": "confirmed",
        },
    ],
    "meal_options": {
        "enabled": True,
        "sample": True,
        "sample_note": "Sample entrées — final menu to be confirmed by the venue.",
        "options": ["Herb-roasted chicken (sample)", "Seared salmon (sample)", "Wild mushroom risotto (sample)"],
        "_status": "placeholder",
    },
    "story": {
        "published": True,
        "label": "Before All This",
        "kicker": "An origin story, abridged",
        "headline": "How It Started",
        "standfirst": "There are several versions of how this started. This is the one we agreed to publish.",
        "intro": "Sophie and Ken worked together at an agency formerly known as FCB. After spending hours stuck in a small conference room working together on a (successful) pitch for Morningstar Farms, Sophie fell madly in love with Ken. Now they're getting married. And neither of them work on Morningstar Farms anymore.",
        "closing": "The story is still in progress. This part has a dress code.",
        "photos": [
            {
                "url": "/photos/sophie-ken-nyac.png",
                "alt": "Illustrated portrait of Sophie and Ken standing together outside the New York Athletic Club entrance",
            },
        ],
        "_status": "confirmed",
    },
    "wedding_party": {
        "published": True,
        "label": "The Wedding Party",
        "headline": "A few people you should know.",
        "intro": "They have known us for years, seen enough, and, for reasons of their own, have agreed to stand beside us anyway.",
        "secondary": "They are not responsible for questions about transportation, timing, or where Ken went.",
        "members": [
            {"name": "[ Name ]", "role": "Maid of Honor", "bio": "Sophie's sister. Has had editorial approval since birth."},
            {"name": "[ Name ]", "role": "Best Man", "bio": "Has known Ken since [ year ]. Several photographs have therefore been withheld."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Met Sophie at [ place ]. Has been answering “one quick question” ever since."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Old friend of Ken's. Knows significantly more than appears on this website."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Has attended enough major Sophie life events to qualify for preferred status."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "One of the few people trusted to give Ken advice, which does not mean Ken consistently takes it."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Friend, confidante, and occasional independent fact-checker."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Has been around long enough to remember at least one version of Ken that will not be discussed during dinner."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Knows where most of the bodies are buried. Figuratively. We believe."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Selected for loyalty, friendship, and an established ability to remain calm in a group chat."},
        ],
        "_status": "placeholder",
    },
    "ny_guide": {
        "published": True,
        "label": "New York, According to Us",
        "headline": "You cannot do New York in a weekend.",
        "subhead": "This has never stopped anyone from trying.",
        "body": "These are the places we would send you when left in charge of your limited time, appetite, and judgment.",
        "disclaimer": "For legal reasons, we should probably mention that most of this is terrible advice.",
        "map_title": "The Manhattan Plan",
        "map_caption": "An efficient way to spend a weekend in New York without accidentally experiencing New York.",
        "map_note": "For an actual recommendation, ask us. We have several.",
        "recommendations": [
            {"num": "01", "category": "Eat", "name": "Olive Garden, Times Square", "body": "New York contains a significant amount of Italian food. We recommend walking past all of it until you reach the Olive Garden. The breadsticks are unlimited. Your time here is not.", "tag": "Sophie + Ken's Definitive Italian", "maps_query": "Olive Garden Times Square New York", "pin": {"x": 47, "y": 36}},
            {"num": "02", "category": "Eat", "name": "Sbarro, Herald Square", "body": "At last: an authentic New York slice, provided your primary source on New York is Michael Scott. Eat it standing up for additional credibility.", "tag": "A New York Institution, Technically", "maps_query": "Sbarro Herald Square New York", "pin": {"x": 45, "y": 42}},
            {"num": "03", "category": "Culture", "name": "M&M'S New York", "body": "A flagship Manhattan destination devoted entirely to answering one question: What if a candy had commercial real estate? Leave only after identifying your Inner M&M, purchasing something nobody required personalized, and reconsidering several decisions.", "tag": "Culture", "maps_query": "M&M'S New York Times Square", "pin": {"x": 46, "y": 35}},
            {"num": "04", "category": "Culture", "name": "Madame Tussauds", "body": "Meet dozens of internationally famous people in one afternoon. None will ask how the wedding planning is going. Take enough photographs that future generations become unclear on whether you once knew Beyoncé.", "tag": "Celebrity Access", "maps_query": "Madame Tussauds New York", "pin": {"x": 45, "y": 38}},
            {"num": "05", "category": "Transportation", "name": "The Central Park Pedicab Experience", "body": "Why walk through Central Park for free when you can watch a per-minute rate convert scenery into a financial instrument? Carefully inspect the posted rate before voluntarily beginning this particular adventure.", "tag": "The Scenic Route to Insolvency", "maps_query": "Central Park Pedicab Tours New York", "pin": {"x": 52, "y": 22}},
            {"num": "06", "category": "Transportation", "name": "The Open-Top Sightseeing Bus", "body": "Experience Midtown traffic from approximately eight feet higher than usual. It is the same red light. Now panoramic.", "tag": "Transit, But Slower", "maps_query": "Hop-On Hop-Off Bus Times Square New York", "pin": {"x": 48, "y": 40}},
            {"num": "07", "category": "People", "name": "Every Costumed Character in Times Square", "body": "Take one photograph with all of them. Elmo. Spider-Man. Minnie Mouse. Batman. A second Spider-Man whose relationship to the first Spider-Man is unclear. Then enjoy the traditional post-photo negotiations.", "tag": "Local Wildlife", "maps_query": "Times Square New York", "pin": {"x": 47, "y": 37}},
            {"num": "08", "category": "People", "name": "The Street CD Collection", "body": "Accept every CD offered to you. By Sunday, you can return home with a physical-media collection representing several artists you have never heard of, and a renewed appreciation for Spotify.", "note": "Please do not actually do this.", "tag": "Support the Arts, In Theory", "maps_query": "Times Square New York", "pin": {"x": 50, "y": 48}},
            {"num": "09", "category": "Shopping", "name": "Macy'S Herald Square", "body": "See every floor. No shortcuts. Tell your group you will meet them “by the shoes,” and discover why this instruction has historically failed.", "tag": "A Brief Errand", "maps_query": "Macy's Herald Square New York", "pin": {"x": 44, "y": 43}},
            {"num": "10", "category": "Shopping", "name": "The Times Square Souvenir Store Challenge", "body": "Purchase an I ❤️ NY shirt. Put it on immediately. Ideally over your existing shirt. The city respects commitment.", "tag": "Dress Like a Local", "maps_query": "Times Square Souvenir Shop New York", "pin": {"x": 46, "y": 39}},
            {"num": "11", "category": "Walk", "name": "The Fifth Avenue Formation", "body": "Walk four abreast. Stop without warning at every intersection. Consult Google Maps while standing directly in the middle of the sidewalk. If you hear a noise from behind you, congratulations: A New Yorker has noticed you.", "tag": "Immersive Cultural Exchange", "maps_query": "Fifth Avenue New York", "pin": {"x": 54, "y": 33}},
            {"num": "12", "category": "See", "name": "The Two-Observation-Deck Doubleheader", "body": "Pay for one aerial view of Manhattan. Then travel several blocks, and pay for another aerial view to confirm Manhattan has remained in roughly the same place. Take approximately 800 versions of the same photograph.", "tag": "Due Diligence", "maps_query": "Top of the Rock New York", "pin": {"x": 49, "y": 45}},
            {"num": "13", "category": "Drink", "name": "A Times Square Rooftop Cocktail", "body": "Choose the roof with the longest elevator line. Order the most expensive vodka soda on the menu. The alcohol will taste exactly like vodka. The soda will taste exactly like soda. The view is what you are paying for, and it is mostly another rooftop.", "tag": "One Drink", "maps_query": "Rooftop Bar Times Square New York", "pin": {"x": 45, "y": 41}},
        ],
        "_status": "confirmed",
    },
    "travel": {
        "published": True,
        "intro": "New York has three airports, several train stations, and an impressive number of ways to take the wrong route. These are the simplest options.",
        "hotels_note": "Room blocks and recommended hotels are being arranged. Details, rates, and booking deadlines will be posted here.",
        "hotels": [],
        "getting_here": [
            {"title": "By plane", "body": "Fly into whichever airport produces the least offensive combination of price and arrival time. JFK, LaGuardia, and Newark all serve the city — allow an hour to Manhattan, more at rush hour."},
            {"title": "By train", "body": "Penn Station and Grand Central are both convenient, depending on where you are coming from, and how strongly you feel about train stations. Amtrak arrives at Moynihan Train Hall; commuter lines at Grand Central. Both are a short ride from the venue."},
            {"title": "By car", "body": "If you are brave enough to drive into Manhattan, valet parking is available at the venue."},
            {"title": "Getting around", "body": "The venue is on Central Park South, and is easy to reach by subway, cab, or a walk in shoes you have planned appropriately."},
        ],
        "_status": "placeholder",
    },
    "attire": {
        "published": True,
        "placeholder": False,
        "headline": "Black Tie Optional",
        "body": "In plain English: tuxedos and floor-length gowns are welcome and encouraged — but a dark suit and tie, or an elegant cocktail dress, is equally at home.",
        "guidance": [
            {"label": "For men", "body": "A tuxedo if you own one — or have been waiting for an excuse. Otherwise, a dark suit and a button-down shirt."},
            {"label": "For women", "body": "A long gown, a cocktail dress, or a dressy suit. If it feels slightly too dressed up for dinner, it is probably correct."},
        ],
        "_status": "confirmed",
    },
    "faqs": [
        {"q": "What time should I arrive?", "a": "Doors open at 5:30 PM at the New York Athletic Club.", "_status": "confirmed"},
        {"q": "Where is the wedding?", "a": "The New York Athletic Club at 180 Central Park South, New York, New York. It is directly across from Central Park, which is helpful both geographically, and aesthetically.", "_status": "confirmed"},
        {"q": "Is the wedding indoors?", "a": "The entire evening takes place at the New York Athletic Club.", "_status": "confirmed"},
        {"q": "What should I wear?", "a": "Black tie optional. Tuxedos, dark suits, gowns, and formal dresses are all appropriate.", "_status": "confirmed"},
        {"q": "Can I bring a guest?", "a": "Your invitation lists everyone in your party. When you RSVP, you'll see exactly who is included — including any plus-one.", "_status": "confirmed"},
        {"q": "Are children invited?", "a": "Unfortunately, they are not.", "_status": "confirmed"},
        {"q": "When should I RSVP?", "a": "As soon as you know your plans. A formal deadline will be announced here.", "_status": "confirmed"},
        {"q": "What happens after 11:30 PM?", "a": "The after-party. More information will follow. For now, assume the evening continues.", "_status": "confirmed"},
    ],
    "registry": {
        "published": True,
        "label": "There Is, Apparently, Also a Registry",
        "headline": "Having you with us is the point.",
        "body": "For those who have asked anyway, we've put a few ideas here.",
        "entries": [
            {"name": "Zola", "kind": "Registry", "note": "Sample link — the couple will replace it with their real registry page.", "url": "https://www.zola.com", "_status": "placeholder"},
            {"name": "The Honeymoon Fund", "kind": "A fund", "note": "Toward a proper trip, taken slowly. Link to come.", "url": "", "_status": "placeholder"},
            {"name": "A Charity Close to Their Hearts", "kind": "In lieu of anything wrapped", "note": "Details to come.", "url": "", "_status": "placeholder"},
        ],
        "_status": "placeholder",
    },
    "rsvp": {
        "personality_question": "What song gets you to the dance floor without fail?",
        "deadline_note": "Kindly reply, one way or the other, at your earliest convenience.",
        "_status": "confirmed",
    },
}

SEED_HOUSEHOLDS = [
    {
        "name": "The Guest Household",
        "members": [
            {"first_name": "Test", "last_name": "Guest", "plus_one_allowed": True},
            {"first_name": "Taylor", "last_name": "Guest", "plus_one_allowed": False},
        ],
    },
    {
        "name": "Alex Sample",
        "members": [
            {"first_name": "Alex", "last_name": "Sample", "plus_one_allowed": True},
        ],
    },
    {
        "name": "The Example Family",
        "members": [
            {"first_name": "Jordan", "last_name": "Example", "plus_one_allowed": False},
            {"first_name": "Riley", "last_name": "Example", "plus_one_allowed": False},
            {"first_name": "Casey", "last_name": "Example", "plus_one_allowed": False},
        ],
    },
]
