# Centralized editable content for sophieandken.
# Every public string on the site comes from here.
# "_status": "confirmed"  -> verified wedding information, safe to publish
# "_status": "placeholder" -> sample/draft, clearly marked, replace before launch
# "_status": "hidden"      -> section framework exists but stays unpublished

CONTENT = {
    "couple": {
        "partner_one": "Sophie Knochenhauer",
        "partner_two": "Ken Syme",
        "display_names": "Sophie + Ken",
        "mark": "SK+KS",
        "_status": "confirmed",
    },
    "date": {
        "display": "Saturday, June 5, 2027",
        "short": "June 5, 2027",
        "stamp": "JUN 05 2027",
        "iso_start": "2027-06-05T17:30:00-04:00",
        "iso_end": "2027-06-06T00:30:00-04:00",
        "_status": "confirmed",
    },
    "venue": {
        "name": "New York Athletic Club",
        "address": "180 Central Park South",
        "city": "New York, New York",
        "maps_query": "New York Athletic Club, 180 Central Park South, New York, NY",
        "_status": "confirmed",
    },
    "issue": {
        "volume": "Vol. I",
        "number": "No. 1",
        "edition": "The Wedding Issue",
        "price_line": "Issued to friends & family",
        "_status": "confirmed",
    },
    "schedule": [
        {
            "time": "5:30 PM",
            "title": "The Arrival",
            "description": "We arrive.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "6:00 PM",
            "title": "The Ceremony",
            "description": "We do.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "6:30 PM",
            "title": "The Cocktail Hour",
            "description": "We drink.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "7:30 – 11:30 PM",
            "title": "The Reception",
            "description": "We eat and dance.",
            "location": "New York Athletic Club",
            "_status": "confirmed",
        },
        {
            "time": "11:30 PM",
            "title": "The After-Party",
            "description": "We carry on.",
            "location": "To be announced",
            "_status": "confirmed",
        },
    ],
    "meal_options": {
        "enabled": True,
        "sample": True,
        "sample_note": "Sample entrées — final menu to be confirmed by the venue.",
        "options": ["Herb-roasted chicken (sample)", "Seared salmon (sample)", "Wild mushroom risotto (sample)"],
        "_status": "placeholder",
    },
    "story": {
        "published": True,
        "label": "Before All This",
        "kicker": "An origin story, abridged",
        "headline": "How It Started",
        "standfirst": "This is the story of how Sophie and Ken met. They call it a plant-based meat-cute.",
        "intro": "Sophie and Ken worked together at an agency formerly known as FCB. After spending hours stuck in a small conference room working together on a (successful) pitch for Morningstar Farms, Sophie fell madly in love with Ken. Now they're getting married. And neither of them works on Morningstar Farms anymore.",
        "closing": "The story is still in progress. This part has a dress code.",
        "photos": [
            {
                "url": "/photos/sophie-ken-booth.jpg",
                "alt": "Black-and-white photograph of Sophie and Ken laughing together in a photo booth",
            },
        ],
        "_status": "confirmed",
    },
    "wedding_party": {
        "published": True,
        "label": "The Wedding Party",
        "headline": "A few people you should know.",
        "intro": "They have known us for years, seen enough, and, for reasons of their own, have agreed to stand beside us anyway.",
        "secondary": "They are not responsible for questions about transportation, timing, or where Ken went.",
        "members": [
            {"name": "[ Name ]", "role": "Maid of Honor", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Best Man", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Bridesmaid", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
            {"name": "[ Name ]", "role": "Groomsman", "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
        ],
        "_status": "placeholder",
    },
    "ny_guide": {
        "published": True,
        "label": "New York, According to Us",
        "headline": "You cannot do New York in a weekend.",
        "subhead": "This has never stopped anyone from trying.",
        "body": "A few places to start. We stand by some of them.",
        "map_title": "The Manhattan Plan",
        "map_caption": "An efficient way to spend a weekend in New York without accidentally experiencing New York.",
        "map_note": "For an actual recommendation, ask us. We have several.",
        "recommendations": [
            {"num": "01", "category": "Eat", "name": "Olive Garden, Times Square", "body": "New York has a lot of Italian restaurants. This one has unlimited breadsticks.", "tag": "Sophie + Ken's Definitive Italian", "maps_query": "Olive Garden Times Square New York", "pin": {"x": 47, "y": 36}},
            {"num": "02", "category": "Eat", "name": "Sbarro, Herald Square", "body": "A New York slice, according to Michael Scott.", "tag": "A New York Institution, Technically", "maps_query": "Sbarro Herald Square New York", "pin": {"x": 45, "y": 42}},
            {"num": "03", "category": "See", "name": "M&M'S New York", "body": "Three floors of M&M's. Somehow, there is an upstairs.", "tag": "Culture", "maps_query": "M&M'S New York Times Square", "pin": {"x": 46, "y": 35}},
            {"num": "04", "category": "See", "name": "Madame Tussauds", "body": "See Beyoncé. Sort of.", "tag": "Celebrity Access", "maps_query": "Madame Tussauds New York", "pin": {"x": 45, "y": 38}},
            {"num": "05", "category": "See", "name": "The Central Park Pedicab Experience", "body": "Central Park, with a meter running.", "tag": "The Scenic Route to Insolvency", "maps_query": "Central Park Pedicab Tours New York", "pin": {"x": 52, "y": 22}},
            {"num": "06", "category": "See", "name": "The Open-Top Sightseeing Bus", "body": "Midtown traffic, from slightly higher up.", "tag": "Transit, But Slower", "maps_query": "Hop-On Hop-Off Bus Times Square New York", "pin": {"x": 48, "y": 40}},
            {"num": "07", "category": "See", "name": "Every Costumed Character in Times Square", "body": "Take the picture. Then begin negotiations.", "tag": "Local Wildlife", "maps_query": "Times Square New York", "pin": {"x": 47, "y": 37}},
            {"num": "08", "category": "See", "name": "The Street CD Collection", "body": "Accept one if you would like the rest of your afternoon to take a turn.", "note": "Actually, don't.", "tag": "Support the Arts, In Theory", "maps_query": "Times Square New York", "pin": {"x": 50, "y": 48}},
            {"num": "09", "category": "Shop", "name": "Macy'S Herald Square", "body": "One quick stop that has never been one quick stop.", "tag": "A Brief Errand", "maps_query": "Macy's Herald Square New York", "pin": {"x": 44, "y": 43}},
            {"num": "10", "category": "Shop", "name": "The Times Square Souvenir Store Challenge", "body": "Buy the shirt. Put it on immediately. Commit.", "tag": "Dress Like a Local", "maps_query": "Times Square Souvenir Shop New York", "pin": {"x": 46, "y": 39}},
            {"num": "11", "category": "Walk", "name": "The Fifth Avenue Formation", "body": "Walk four across. Stop suddenly. Become part of the ecosystem.", "tag": "Immersive Cultural Exchange", "maps_query": "Fifth Avenue New York", "pin": {"x": 54, "y": 33}},
            {"num": "12", "category": "See", "name": "The Two-Observation-Deck Doubleheader", "body": "See Manhattan from above. Then pay to make sure it is still there.", "tag": "Due Diligence", "maps_query": "Top of the Rock New York", "pin": {"x": 49, "y": 45}},
            {"num": "13", "category": "Drink", "name": "A Times Square Rooftop Cocktail", "body": "A vodka soda. But higher up.", "tag": "One Drink", "maps_query": "Rooftop Bar Times Square New York", "pin": {"x": 45, "y": 41}},
        ],
        "_status": "confirmed",
    },
    "attire": {
        "published": True,
        "placeholder": False,
        "headline": "Black Tie Optional",
        "body": "In plain English: tuxedos and floor-length gowns are welcome — but a dark suit and tie, or an elegant cocktail dress, is equally at home.",
        "guidance": [
            {"label": "For men", "body": "A tuxedo if you own one — or have been waiting for an excuse. Otherwise, a dark suit and a button-down shirt."},
            {"label": "For women", "body": "A long gown, a cocktail dress, or a dressy suit. If it feels slightly too dressed up for dinner, it is probably correct."},
        ],
        "_status": "confirmed",
    },
    "faqs": [
        {"q": "What time should I arrive?", "a": "Doors open at 5:30 PM at the New York Athletic Club.", "_status": "confirmed"},
        {"q": "Where is the wedding?", "a": "The New York Athletic Club at 180 Central Park South, New York, New York. It is directly across from Central Park, which is helpful both geographically, and aesthetically.", "_status": "confirmed"},
        {"q": "Is the wedding indoors?", "a": "The entire evening takes place at the New York Athletic Club.", "_status": "confirmed"},
        {"q": "What should I wear?", "a": "Black tie optional. Tuxedos, dark suits, gowns, and formal dresses are all appropriate.", "_status": "confirmed"},
        {"q": "Can I bring a guest?", "a": "Your invitation lists everyone in your party. When you RSVP, you'll see exactly who is included — including any plus-one.", "_status": "confirmed"},
        {"q": "Are children invited?", "a": "Unfortunately, they are not.", "_status": "confirmed"},
        {"q": "When should I RSVP?", "a": "As soon as you know your plans. A formal deadline will be announced here.", "_status": "confirmed"},
        {"q": "What happens after 11:30 PM?", "a": "The after-party. More information will follow. For now, assume the evening continues.", "_status": "confirmed"},
    ],
    "registry": {
        "published": True,
        "label": "There Is, Apparently, Also a Registry",
        "headline": "The Registry",
        "subhead": "A few things we’re into. Not needed. But appreciated.",
        "body": "Having you with us is the point.",
        "note": "For those who have asked, we’ve put together a few things we love, a few things we need, and a few things we did not realize we had opinions about until now.",
        "signoff": "Love, Sophie & Ken",
        "entries": [
            {"name": "MyRegistry", "kind": "Registry, honeymoon fund, and charity", "note": "One list for all of it.", "url": "https://www.myregistry.com/giftlist/sophieandken", "_status": "confirmed"},
        ],
        "_status": "confirmed",
    },
    "rsvp": {
        "personality_question": "What song gets you to the dance floor without fail?",
        "deadline_note": "Kindly reply, one way or the other, by April 5, 2027.",
        "_status": "confirmed",
    },
}

SEED_HOUSEHOLDS = [
    {
        "name": "The Guest Household",
        "members": [
            {"first_name": "Test", "last_name": "Guest", "plus_one_allowed": True},
            {"first_name": "Taylor", "last_name": "Guest", "plus_one_allowed": False},
        ],
    },
    {
        "name": "Alex Sample",
        "members": [
            {"first_name": "Alex", "last_name": "Sample", "plus_one_allowed": True},
        ],
    },
    {
        "name": "The Example Family",
        "members": [
            {"first_name": "Jordan", "last_name": "Example", "plus_one_allowed": False},
            {"first_name": "Riley", "last_name": "Example", "plus_one_allowed": False},
            {"first_name": "Casey", "last_name": "Example", "plus_one_allowed": False},
        ],
    },
]
